### ISSUE TITLE
waitForDeployment function does not work and contract.target should be replaced with contract.address

### ISSUE THREAD

**Issue by Taneristique** [SigmaGmbH/swisstronik-tutorials#10]
waitForDeployment function does not work and gives me following error.

![bug](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/48108872/62a743f3-70d5-4c2e-a261-b874c99c86b1)

I resolved error when I removed waitForDeployment() function however I lived a second problem because of the following line
  console.log(`Swisstronik contract deployed to ${contract.target}`).Here I put the proof of problem: 

![bug2](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/48108872/0f47d700-4ad1-4f3e-8768-a06b68ad78b9)

I changed contract.target as contract.address and removed waitForDeployment () then both of the problems ,that I stated above, are resolved. I put the image that proves the problems are resolved:

![normal](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/48108872/a46adc51-dae3-4c19-b37e-beb34f9db034)

As a result, I suggest doing following modifications in [ethereum network deployment documentation](https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/ERC20_interaction/scripts/deploy.js) and [Contract_deployment _hardhat](https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/Contract_deployment%20_hardhat/scripts/deploy.js)
1. Removing waitForDeployment() 
2. Replacing contract.target with 
contract.address as it is also shown in following documentation [hardhat contract deployment](https://hardhat.org/tutorial/deploying-to-a-live-network).
I know this modifications are already done in [PERC20_interaction/scripts/deploy.js](https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/PERC20_interaction/scripts/deploy.js) but it can be better if you apply same modifications to these files too  in order to prevent misunderstandings on deployment step for new developpers : [ethereum network deployment documentation](https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/ERC20_interaction/scripts/deploy.js) and [Contract_deployment _hardhat](https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/Contract_deployment%20_hardhat/scripts/deploy.js), [swisstronik-docs](https://swisstronik.gitbook.io/swisstronik-docs/build-on-swisstronik/contract-deployment-hardhat/4.-deploy-the-smart-contract)

**Comment by SantiagoDevRel** [comment]
Hi @Taneristique thanks for submitting the report.
I think this issue could be related to your Hardhat version (maybe check if you have a global Hardhat version on your machine), I just ran the script and it worked well.
![image](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/83420872/809b3f4e-59d3-4629-9fa1-649e850a716a)
