### ISSUE TITLE
Private-Key Testnet Exposed

### ISSUE THREAD

**Issue by warifp** [SigmaGmbH/swisstronik-tutorials#2]
URL: https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/ERC20_interaction/hardhat.config.js

* Found Private-Key : d5a63c3b252ef2ac23a65320e6e79e5ddd36dd477b9ee20e86e8c0b7d74e80f4
* In Private-key have a address: 0x16af037878a6cAce2Ea29d39A3757aC2F6F7aac1
* This Address and I think this is the Tesnet Address that the Swisstronik Team uses (https://explorer-evm.testnet.swisstronik.com/address/0x16af037878a6cAce2Ea29d39A3757aC2F6F7aac1)

Even though it is a testnet, it is still exposure data for the team's professionalism. Hackers can send testnet tokens to their wallets, as I know there is only 1 Swisstronik SWTR faucet per wallet.

**Comment by SantiagoDevRel** [comment]
Thanks for the head up!
