### ISSUE TITLE
SwissTronik Extension Sign 

### ISSUE THREAD

**Issue by ltk-arch** [SigmaGmbH/swisstronik-tutorials#27]
I'm not sure if this is a bug, but whenever I try to sign something with the extension in brave, these random characters appear.

<img width="374" alt="Screenshot 2024-08-12 at 14 50 17" src="https://github.com/user-attachments/assets/c946bb95-7795-4fe7-89d0-9fe2f541ada8">

**Comment by vadimburmich** [comment]
It's not an error, it's a message sent by specific dApp and the web extension just shows it.
