### ISSUE TITLE
When trying to mint the PERC20, I keep getting this error. I'm maiking use of this ```https://json-rpc.testnet.swisstronik.com/``` url 

### ISSUE THREAD

**Issue by sublime247** [SigmaGmbH/swisstronik-tutorials#33]
<img width="1172" alt="Screenshot 2024-10-01 at 16 59 44" src="https://github.com/user-attachments/assets/0fd0cd1b-aae4-4069-8c12-45dcf990270a">

**Comment by MikkySnow** [comment]
Looks like you're trying to send unencrypted transaction to endpoint for encrypted ones

https://json-rpc.testnet.swisstronik.com – accepts only encrypted txs, when
https://json-rpc.testnet.swisstronik.com/unencrypted – accepts regular EVM transactions
