### ISSUE TITLE
Error: configuration on package.json

### ISSUE THREAD

**Issue by warifp** [SigmaGmbH/swisstronik-tutorials#4]
I read this repo using .js not .ts

I looked at the README.md documentation section, how to Testing and Deployment: npm run deploy : https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/PERC20_interaction/README.md

When I run "npm run deploy" an error appears like this

```
> deploy
> hardhat run scripts/deploy.ts

Error HH601: Script scripts/deploy.ts doesn't exist.

HardhatError: HH601: Script scripts/deploy.ts doesn't exis
```

it turns out that the **package.json** code is like this, when deploying the script he runs _hardhat run scripts/deploy.ts_, it should be **_deploy.js_** not **_deploy.ts_**

```
"scripts": {
    "compile": "hardhat compile",
    "test": "hardhat test",
    "deploy": "hardhat run scripts/deploy.ts"
  }
```

**Comment by warifp** [comment]
This is the correct one

```
"scripts": {
    "compile": "hardhat compile",
    "test": "hardhat test",
    "deploy": "hardhat run scripts/deploy.ts"
  }
```
Because in the scripts folder there is only .js (deploy.js)

**Comment by warifp** [comment]
This is the correct one

```
"scripts": {
    "compile": "hardhat compile",
    "test": "hardhat test",
    "deploy": "hardhat run scripts/deploy.js"
  }
```

Because in the scripts folder there is only .js (deploy.js)

**Comment by SantiagoDevRel** [comment]
Answered here https://github.com/SigmaGmbH/swisstronik-tutorials/issues/5
