### ISSUE TITLE
Error: undefined: When using ${perc20.address} method to print out the deployed contract in Hardhat@^2.17.4 

### ISSUE THREAD

**Issue by Ignatiusdork** [SigmaGmbH/swisstronik-tutorials#7]
when I try to deploy a contract (npx hardhat run) I get a printout in the console like this:

npx hardhat run

```
> npx hardhat run scripts/deploy.js --network swisstronik

PERC20Sample was deployed to undefined
```

After some trial and error, it turned out it had to do with a change in the method used in the different hardhat versions, in the source code directory "scripts/deploy.js" is a

```
const { ethers } = require("hardhat");

async function main() {
  const perc20 = await ethers.deployContract("PERC20Sample");
  await perc20.waitForDeployment();

  console.log(`PERC20Sample was deployed to ${perc20.address}`);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```
It should be `${perc20.address}`; replaced with await `${perc20.target}`; for hardhat versions @^3.0.0 and @^2.17.4

 ***
Conclusion

1. `${perc20.target}`; only for hardhat-toolbox@^3.0.0 and hardhat@^2.17.1
2. `${perc20.address}`; is with hardhat-toolbox@^1.0.2 and hardhat@^2.12.7 

So the correct script is

```
const { ethers } = require("hardhat");

async function main() {
  const perc20 = await ethers.deployContract("PERC20Sample");
  await perc20.deployed();

  console.log(`PERC20Sample was deployed to ${perc20.target}`);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```

**Comment by Ignatiusdork** [comment]
Proof

![Screenshot at 2023-09-28 20-06-34](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/49357127/7b423674-1122-4977-8496-559c8edcdfb3)

**Comment by Ignatiusdork** [comment]
Proof 

![Screenshot at 2023-09-28 20-06-34](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/49357127/166cc814-3ef7-47e7-94dd-dae2a60d4360)

**Comment by SantiagoDevRel** [comment]
Because this issue is relatively minor, we'd like to express our appreciation by offering you a reward of 25usdt & 25usd in SWTR tokens. Your name will be added to our [Hall of Fame](https://github.com/SigmaGmbH/Bug-Bounty-1.0/tree/main/Hall%20Of%20Fame) today. Thank you for your valuable contribution
