### ISSUE TITLE
Writing errors in README.md make developers confused [not .ts just .js]

### ISSUE THREAD

**Issue by chainzoku** [SigmaGmbH/swisstronik-tutorials#8]
I found several typos in README.md.

If people are confused about how to develop.
You use .ts even though the source code uses .js in [README.md](https://github.com/SigmaGmbH/swisstronik-tutorials/tree/main/PERC20_interaction#readme)

![image](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/138441009/b2aea518-782f-47fc-82c0-95ef8b79124d)

**Comment by SantiagoDevRel** [comment]
Thanks for submitting this report, here is your reward: 
https://github.com/SigmaGmbH/Bug-Bounty-1.0/blob/main/Hall%20Of%20Fame/bug_report_by_chainzoku.md
