### ISSUE TITLE
The presence of Lock.js in the test folder.

### ISSUE THREAD

**Issue by kaksv** [SigmaGmbH/swisstronik-tutorials#9]
I think the Lock.js in the test folder is redundant and deleting it is better than leaving it as part of the code. This file is found under contract_deployment_hardhat folder. 

There is also another Lock.js in the test folder under ERC20_interaction folder

**Comment by warifp** [comment]
In my opinion, when we create hardhat code with "npx hardhat", then in the Contracts folder there will be a Lock.sol file and when deployed it will produce Lock.js in the Test Folder.
Yes, that's right, in my opinion, just delete it because it's not needed.

**Comment by SantiagoDevRel** [comment]
Hi @kaksv, we appreciate your feedback. This issue doesn't have a significant impact on the overall tutorial or documentation. Thank you for bringing it to our attention.
